version: '3.5'

services:
    frontend:
        image: frontend-example
        environment:
            - API_URL=http://localhost:8000
        ports:
            - 5000:5000
        container_name: frontend
    backend:
        image: backend-example
        environment:
            - FRONT_URL=http://localhost:5000
            - REDIS=redis
            - DB_USERNAME=root
            - DB_PASSWORD=salasana
            - DB_NAME=backend
            - DB_HOST=db
        ports:
            - 8000:8000
        container_name: backend
        depends_on:
            - db
    db:
        image: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=salasana
            - POSTGRES_DB=backend
    redis:
        image: redis
        restart: unless-stopped
    nginx:
        image: nginx
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
