version: '3.5'

services:
    frontend:
        image: frontend-example
        environment:
            - API_URL=http://localhost:8000
        ports:
            - 5000:5000
    backend:
        image: backend-example
        environment:
            - FRONT_URL=http://localhost:5000
            - REDIS=redis
            - DB_USERNAME=root
            - DB_PASSWORD=salasana
            - DB_NAME=backend
            - DB_HOST=db
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=salasana
            - POSTGRES_DB=backend
        volumes:
            - ./database:/var/lib/postgresql/data
    redis:
        image: redis
        restart: unless-stopped
